### PR TITLE
Added support to end participation in study

### PR DESCRIPTION
**Pull request by alena456**
closes https://github.com/NUMde/compass-numapp-backend/issues/36

### CODE REVIEW

**Comment by mbastian93** [comment]
Why did you name the variable "subjectParticipation" instead of just "status" (which would be what [orscf](https://orscf.org/sms-model/) uses) or at least "participationStatus"?

**Comment by alena456** [comment]
> Why did you name the variable "subjectParticipation" instead of just "status" (which would be what [orscf](https://orscf.org/sms-model/) uses) or at least "participationStatus"?

I was referring to this [swagger](https://orscf.org/ims-swagger/). Do you know how the model maps to the Swagger definition? The Subject in the model doesn't match the SubjectIdentities Sektion in the Swagger. We could also use "status" if you prefer.

**Comment by mbastian93** [comment]
> > Why did you name the variable "subjectParticipation" instead of just "status" (which would be what [orscf](https://orscf.org/sms-model/) uses) or at least "participationStatus"?
> 
> I was referring to this [swagger](https://orscf.org/ims-swagger/). Do you know how the model maps to the Swagger definition? The Subject in the model doesn't match the SubjectIdentities section in the Swagger. We could also use "status" if you prefer.

After some research: what i linked is seemingly not strictly part of orscf. What i linked refers to the the [HL7 definition of a study participant](https://www.hl7.org/fhir/researchsubject-definitions.html#ResearchSubject.status). 
So i would still suggest that we follow that naming convention.

**Review by mahvaezi — COMMENTED** [review]
Please Remove the local Questionnaire.
https://github.com/NUMde/compass-numapp-backend/blob/fc690cccc3d183667cfef89c5b637d0a71e967d8/db/migration/V002__Initial_Data.sql#L6

**Comment by alena456** [comment]
> HL7 definition of a study participant

Alles klar, dann benenne ich die Property zu "status" um.

**Comment by alena456** [comment]
New change is pushed

**Review by mbastian93 — APPROVED** [review]

**Comment by alena456** [comment]
@mahvaezi @mbastian93 Do you want to merge or should I?

**Pull request merged**
